var classes = [
    {
        "name": "App\\Http\\Controllers\\Admin\\GajiMassalController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "langkahSatu",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "langkahDua",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "simpan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cekGajiSudahAda",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 6,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pegawai",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Pegawai",
            "App\\Models\\Divisi",
            "App\\Models\\Tim",
            "App\\Models\\Jabatan",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pegawai",
            "App\\Models\\MasterTunjangan",
            "App\\Models\\MasterPotongan",
            "Illuminate\\Http\\Request",
            "App\\Models\\Gaji",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pegawai"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 252,
        "vocabulary": 90,
        "volume": 1635.95,
        "difficulty": 8.98,
        "effort": 14693.96,
        "level": 0.11,
        "bugs": 0.55,
        "time": 816,
        "intelligentContent": 182.14,
        "number_operators": 39,
        "number_operands": 213,
        "number_operators_unique": 7,
        "number_operands_unique": 83,
        "cloc": 8,
        "loc": 75,
        "lloc": 67,
        "mi": 60.95,
        "mIwoC": 36.72,
        "commentWeight": 24.23,
        "kanDefect": 0.91,
        "relativeStructuralComplexity": 2025,
        "relativeDataComplexity": 0.11,
        "relativeSystemComplexity": 2025.11,
        "totalStructuralComplexity": 8100,
        "totalDataComplexity": 0.43,
        "totalSystemComplexity": 8100.43,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 1,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    }
]