var classes = [
    {
        "name": "App\\Http\\Controllers\\Pegawai\\PegawaiGajiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unduhSlipGaji",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Pegawai",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Gaji",
            "App\\Models\\Gaji",
            "App\\Models\\Gaji",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Pegawai",
            "Barryvdh\\DomPDF\\Facade\\Pdf"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 135,
        "vocabulary": 59,
        "volume": 794.16,
        "difficulty": 5.94,
        "effort": 4719.99,
        "level": 0.17,
        "bugs": 0.26,
        "time": 262,
        "intelligentContent": 133.62,
        "number_operators": 30,
        "number_operands": 105,
        "number_operators_unique": 6,
        "number_operands_unique": 53,
        "cloc": 22,
        "loc": 63,
        "lloc": 41,
        "mi": 83.48,
        "mIwoC": 43.84,
        "commentWeight": 39.64,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 0.26,
        "relativeSystemComplexity": 324.26,
        "totalStructuralComplexity": 648,
        "totalDataComplexity": 0.53,
        "totalSystemComplexity": 648.53,
        "package": "App\\Http\\Controllers\\Pegawai\\",
        "pageRank": 1,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    }
]